ch18/pizza_blog/pizza_blog_app/urls.py
"""URL patters for pizza_blog_app"""
from django.urls import path
from . import views
app_name = 'pizza_blog_app'
urlpatterns = [
    # home page
    path('', views.index, name='index'),
    # pizzas list
    path('pizzas/', views.pizzas, name='pizzas'),
    # pizza topping list
    path('pizza/<int:pizza_id>/', views.pizza, name='pizza'),
]

ch18/pizza_blog/pizza_blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizza_blog_app.urls')),

]

ch18/pizza_blog/pizza_blog_app/models.py
from django.db import models

class Pizza(models.Model):
    """A kind of pizza, like 'Hawaiian' or 'Meat Lovers'"""
    name = models.CharField(max_length=128)

class Topping(models.Model):
    """A topping for pizza, like 'Sausage' or 'Mushroom'"""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)

ch18/pizza_blog/pizza_blog_app/views.py
from django.shortcuts import render

from .models import Pizza

def index(request):
    """The homepage for Pizza Blog App"""
    return render(request, 'pizza_blog_app/index.html')

def pizzas(request):
    """Show all the pizzas"""
    pizzas = Pizza.objects.order_by('name')
    context = {'pizzas': pizzas}
    return render(request, 'pizza_blog_app/pizzas.html', context)

def pizza(request, pizza_id):
    """Show the toppings for a pizza"""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('name')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizza_blog_app/pizza.html', context)

ch18/pizza_blog/pizza_blog_app/templates/pizza_blog_app/base.html
<p>
    <a href="{% url 'pizza_blog_app:index' %}">PizzaBlogApp</a>
    -
    <a href="{% url 'pizza_blog_app:pizzas' %}">Pizzas</a>
</p>

{% block content %}{% endblock content %}

ch18/pizza_blog/pizza_blog_app/templates/pizza_blog_app/index.html
{% extends "pizza_blog_app/base.html" %}

{% block content %}
<p>Pizza Blog App tracks pizzas I like and their toppings</p>
<p>Not PBR</p>
{% endblock content %}

ch18/pizza_blog/pizza_blog_app/templates/pizza_blog_app/pizza.html
{% extends "pizza_blog_app/base.html" %}

{% block content %}

<p>Pizza: {{ pizza.name }}</p>

<p>Toppings:</p>

<ul>
    {% for topping in toppings %}
    <li>{{ topping.name }}</li>
    {% empty %}
    <li>No toppings for this pizza yet!</li>
    {% endfor %}
</ul>

{% endblock content %}

ch18/pizza_blog/pizza_blog_app/templates/pizza_blog_app/pizzas.html
{% extends "pizza_blog_app/base.html" %}

{% block content %}

<p>Pizzas</p>

<ul>
    {% for pizza in pizzas %}
    <li><a href="{% url 'pizza_blog_app:pizza' pizza.id %}">{{ pizza.name }}</a></li>
    {% empty %}
    <li>No pizzas yet!</li>
    {% endfor %}
</ul>

{% endblock content %}