ch19/blog/articles/urls.py
"""Defines URL patterns for learning_logs"""
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    # home page
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('edit/<int:article_id>/', views.edit, name='edit'),
]

ch19/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('users/', include('users.urls')),
]

ch19/blog/users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    # include default auth urls
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

ch19/blog/articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    """A blog article"""
    title = models.CharField(max_length=256)
    date_added = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    
    def __str__(self):
        """string representation of the model"""
        return self.title

ch19/blog/users/models.py
from django.db import models

# Create your models here.

ch19/blog/articles/forms.py
from django import forms

from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title','body',]

ch19/blog/articles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Article
from .forms import ArticleForm

def index(request):
    """Show all Topics"""
    articles = Article.objects.order_by('date_added')
    context = {'articles': articles}
    return render(request, 'index.html', context)

@login_required
def new(request):
    """Add a new article"""
    if request.method != 'POST':
        # no data submitted, create a black form
        form = ArticleForm()
    else:
        # form submitted, process the submission
        form = ArticleForm(data = request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
        return redirect('articles:index')
    
    # Display a blank or invalid form
    context = {'form': form }
    return render(request, 'new.html', context)

@login_required
def edit(request, article_id):

    article = Article.objects.get(id = article_id)
    if article.author != request.user:
        return redirect('articles:index')

    if request.method != 'POST':
        # no data submitted, create a black form
        form = ArticleForm(instance = article)
    else:
        # form submitted, process the submission
        form = ArticleForm(instance = article, data = request.POST)
        if form.is_valid():
            form.save()
        return redirect('articles:index')
    
    # Display a blank or invalid form
    context = {'article': article, 'form': form }
    return render(request, 'edit.html', context)

ch19/blog/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # display blank registration form
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home
            login(request, new_user)
            return redirect('articles:index')
    # Display the form
    context = { 'form': form }
    return render(request, 'registration/register.html', context)
    

ch19/blog/articles/templates/base.html
<p>
    <a href="{% url 'articles:index' %}">Articles</a>
    -
    {% if user.is_authenticated %}
      {{ user.username }}
      <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
      <a href="{% url 'users:register' %}">Register</a>
      <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>

{% block content %}{% endblock content %}

ch19/blog/articles/templates/edit-test.html
<p>Test</p>

<p>Placeholder</p>

ch19/blog/articles/templates/edit.html
<p>Add a new article</p>

<form action="{% url 'articles:edit' article.id %}" method="post">
{% csrf_token %}
{{ form.as_p }}
<button name="submit">Save article</button>

ch19/blog/articles/templates/index.html
{% extends 'base.html' %}

{% block content %}

<p>Articles</p>

<p><a href="{% url 'articles:new' %}">new</a>

<ul>
    {% for article in articles %}
        <li>
            <p>article: {{ article }}</p>
            <p>body: {{ article.body }}</p>
            <p>date: {{ article.date_added }}</p>
            <p><a href="{% url 'articles:edit' article.id %}">edit</a>
        </li>
    {% empty %}
        <li>No articles have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}

ch19/blog/articles/templates/new.html
<p>Add a new article</p>

<form action="{% url 'articles:new' %}" method="post">
{% csrf_token %}
{{ form.as_p }}
<button name="submit">Add article</button>

ch19/blog/articles/templates/scratch.html
            <p><a href="{% url 'articles:edit' article.id %}">edit</a>
            <p><a href="{% url 'articles:index' %}">index</a>